### ISSUE TITLE
xicam installation on CentOS 7

### ISSUE THREAD

**Issue by ashakim87** [ronpandolfi/Xi-cam#22]
Hi All, I am very new to Linux. My friend wants me to install Xi-cam on a VM which is running CentOS 7. He got the instruction which can be accessed from here: https://docs.google.com/document/d/1CwkUIUgBSktmgt9KfJ0aIdnhO7TKBQRHWIDJXDJVcrU/edit?ts=5841a62c
On step 4d as it say to run "pip install ." inside the Xi-cam folder, it gives error about Qt4 libraries. I then found that I should install it with "conda install pyqt=4", then everything went well. But at the end, when I run xicam, it says "segmentation fault (core dumped)". I tried the same steps on Ubuntu 16.04, the same result. I would appreciate if I can get a step-by-step instruction to install it.

**Comment by ronpandolfi** [comment]
Most likely this is an issue with the PySide distributed through anaconda,
which I think is broken. Please check that the following command executes
successfully:

python -c "from PySide import QtUiTools"

If that fails, you need to install PySide outside of anaconda. I suggest
installing it through your package manager, yum, if possible, or otherwise
through pip. Make sure that the install location is included in Python PATH.

**Comment by ashakim87** [comment]
The command (python -c "from PySide import QtUiTools"), runs successfully. It doesn't show any error message, it also doesn't show any other messages. Still when I run "pip install ." under Xi-cam directory, I get error. I attached the error message here.
[ErrorMsg.txt](https://github.com/ronpandolfi/Xi-cam/files/781088/ErrorMsg.txt)

I can get rid of the error message with these two commands:

`yum install gcc gcc-c++ libtool automake autoconf cmake python-devel libxml2-devel libpng-devel libxslt-devel curl-devel freetype-devel mesa-libGL-devel mysql-server mysql-devel libvorbis-devel`
`conda install pyqt=4`

And all the other steps go fine. But at the end when I try to run 'import dxchange, tomopy' in ipython shell or run xicam, it gives an error message as "Segmentation fault (core dumped)". I have no idea.

**Comment by ronpandolfi** [comment]
The tomopy developers will probably be more helpful for you on the seg fault. You can post a similar issue in the tomopy github repo: https://github.com/tomopy/tomopy/issues

You'll need to correct your installation of tomopy/dxchange. You can try installing it from source by cloning the repository and `pip install .` in that directory.

Pyqt is not required. Xi-cam instead uses the PySide package.

Since you PySide install is working, you can bypass installing it by running (in the source dir) `pip install . --no-deps`

With the above method, some other required dependencies may not be installed, however Xi-cam will notify you of what is missing you run it.

**Comment by ashakim87** [comment]
Thank you for the information, but it didn't help. Installing dxchange/tomopy from source works fine, but at the end when I run xicam it gives error "segmentation fault (core dumped)". I did install all other dependencies it is asking for. I am going to post this issue on the tomopy page. Thanks

**Comment by ashakim87** [comment]
I was finally able to correctly install and run Xi-cam on CentOS 7. Here are the steps I did:

1. yum update
2. yum groupinstall “GNOME Desktop”
3. Reboot the machine, login and type startx
4. Open a terminal
5. sudo yum group mark install "Development Tools"
6. sudo yum group update "Development Tools"
7. Download miniconda2 for Python2.7 from http://conda.pydata.org/miniconda.html and then install it by typing bash Miniconda3-latest-Linux-x86_64.sh
8. Restart terminal
9. sudo yum install qt-webkit-devel libxml2-devel libxslt-devel rpmdevtools gcc gcc-c++ qt-devel cmake python-devel python-pip
10. pip install numpy scipy
11. sudo ln -s /usr/bin/qmake-qt4 /usr/bin/qmake
12. conda install pyside (to downgrade qt to 4.8.5)
13. conda install -c dgursoy tomopy
14. pip install xicam
15. xicam

It may help someone else.
